### ISSUE TITLE
Error reproduction

### ISSUE THREAD

**Issue by LYF199903** [realcrane/BASAR-Black-box-Attack-on-Skeletal-Action-Recognition#4]
Step #249...
        Delta step...
        #1
        Epsilon step...
        #1
Epsilon: 0.0017578124534338713
Mean Squared Error: 0.01861550472676754
Calls: 1785
Attack Class: tensor([21], device='cuda:0')
Target Class: tensor([26], device='cuda:0')
Initial Class:tensor([39], device='cuda:0')
Delta: 0.03429355281207133
n target:: 1
 ----------------------------------------------------------------
 APMonitor, Version 1.0.3
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :            0
   Constants    :            0
   Variables    :         4680
   Intermediates:            0
   Connections  :            0
   Equations    :          118
   Residuals    :          118
 
 Number of state variables:           4680
 Number of total equations: -            0
 Number of slack variables: -            0
 ---------------------------------------
 Degrees of freedom       :           4680
 
 Number of bound variables: -         1260
 
 solver            3  not supported
 using default solver: APOPT
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
 Insufficient workspace (3)
 
 ---------------------------------------------------
 Solver         :  IPOPT (v3.12)
 Solution time  :   4.349999999976717E-002 sec
 Objective      :    248.184961896262     
 Unsuccessful with error code            0
 ---------------------------------------------------
 
 Creating file: infeasibilities.txt
 @error: Solution Not Found

Traceback (most recent call last):
  File "untargeted_attack_op_stgcn_hdm05.py", line 436, in <module>
    main(args)
  File "untargeted_attack_op_stgcn_hdm05.py", line 325, in main
    w, straetgy=2)
  File "../tools/optimization.py", line 161, in op_angle
    m.solve()
  File "/home/jt/.conda/envs/mdm/lib/python3.7/site-packages/gekko/gekko.py", line 2169, in solve
    raise Exception(apm_error)
Exception: @error: Solution Not Found

**Comment by LYF199903** [comment]
I saw the solution to # 3, but it didn't solve my problem
